### ISSUE TITLE
Install section

### ISSUE THREAD

**Issue by AydinHassan** [php-school/php-school.github.io#29]
For Windows, Linux & Mac OS

We need all the steps and possible hurdles, including how to upgrade PHP and so on.

WIP here: https://github.com/php-school/php-school.github.io/tree/install-page

**Comment by mikeymike** [comment]
@AydinHassan  @OliverChenery 

Windows instructions. Let me know if you guys think they need a little more details. 

---

# Windows Installation Docs

## Intro 

Windows is a difficult system to cater for in the PHP world. Unfortunately it has varioius differences on the CMD and console emulators which PHP unfortunately doesn't support. 

To resolve this the best way to get tools such as PHP School Workshops you will need to have installed Cygwin + ConEmu. Once the initial setup of these are complete the process of installing workshops is the same as Linux and Mac operating systems. 

## Cygwin Installation

_**Note:** Cygwin will also install PHP for you :)_

1. Head on over to [https://cygwin.com/install.html](https://cygwin.com/install.html) and grab the latest installer for your system, 32-bit || 64-bit.

2. Run the installer, we chose default values until the package selection point

3. Ensure you choose to install **all PHP packages**. We also recommend installing **GIT** and **VIM** to complete your CLI experience.

4. Complete the installation.  

## ConEmu Installation

1. Grab the installer from [https://conemu.github.io/](https://conemu.github.io/)

2. Run the installer and open ConEmu. 

3. Select Cygwin Bash

## Composer Installation

1. We recommend using the Composer installer found here [https://getcomposer.org/doc/00-intro.md#using-the-installer](https://getcomposer.org/doc/00-intro.md#using-the-installer)

2. Restart ConEmu and then run `composer` to ensure it's running.

**Comment by AydinHassan** [comment]
This is live now
